version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  createChangeSet:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - run: |
          sudo apt-get install python-dev
      - aws-cli/install
      - run: |
          PARAMETERS="KeyPair=$KEY_PAIR "
          PARAMETERS+="NATInstClass=$NAT_INST_CLASS "
          PARAMETERS+="ECSInstClass=$ECS_INST_CLASS "
          PARAMETERS+="ECSInstMin=$ECS_INST_MIN "
          PARAMETERS+="ECSInstMax=$ECS_INST_MAX "
          PARAMETERS+="CertificateArn=$CERTIFICATE_ARN "
          PARAMETERS+="NATSSHCidrAllow=$NAT_SSH_CIDR_ALLOW "
          PARAMETERS+="RedisInstClass=$REDIS_INST_CLASS "
          PARAMETERS+="RedisInstNum=$REDIS_INST_NUM "
          PARAMETERS+="RDSStorage=$RDS_STORAGE "
          PARAMETERS+="RDSInstClass=$RDS_INST_CLASS "
          PARAMETERS+="RDSMasterUser=$RDS_MASTER_USER "
          PARAMETERS+="RDSMasterPass=$RDS_MASTER_PASS "

          mkdir workspace
          aws cloudformation deploy --stack-name $STACK_NAME --no-execute-changeset --capabilities CAPABILITY_IAM --template-file template.yml --parameter-overrides $PARAMETERS | tee workspace/changeset.txt
          CHANGE_SET_NAME=$(grep -o "arn:aws:cloudformation.*" workspace/changeset.txt)
          echo $CHANGE_SET_NAME >> workspace/changesetname.txt
          echo $CHANGE_SET_NAME
      - persist_to_workspace:
          root: workspace
          paths:
            - changesetname.txt
  executeChangeSet:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - attach_workspace:
          at: workspace
      - run: |
          sudo apt-get install python-dev
      - aws-cli/install
      - run: |
          CHANGE_SET_NAME=$(cat workspace/changesetname.txt)
          aws cloudformation execute-change-set --change-set-name $CHANGE_SET_NAME
          aws cloudformation wait stack-update-complete --stack-name $STACK_NAME
  deleteChangeSet:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - attach_workspace:
          at: workspace
      - run: |
          sudo apt-get install python-dev
      - aws-cli/install
      - run: |
          CHANGE_SET_NAME=$(cat workspace/changesetname.txt)
          aws cloudformation delete-change-set --change-set-name $CHANGE_SET_NAME
        
workflows:
  changeset_review_execute:
    jobs:
      - createChangeSet
      - reviewChangeSet:
          type: approval
          requires:
            - createChangeSet
          filters:
            branches:
              only:
                - master
      - executeChangeSet:
          requires:
            - reviewChangeSet
          filters:
            branches:
              only:
                - master
      - deleteChangeSet:
          requires:
            - createChangeSet
          filters:
            branches:
              ignore:
                - master